### ISSUE TITLE
I can't compile "Makefile"

### ISSUE THREAD

**Issue by nassau-tk** [tpunix/pgftool#2]
I'm an amature.
If there are impoliteness and a mistake, I'm sorry.

I want use this PGF Tool.
So, I try compiled. (MinGW installed.)
But,Maybe not complete the compile.
![image](https://user-images.githubusercontent.com/48179091/99182571-026a9e80-2779-11eb-9809-dff6df7696fe.png)

When how doing do, can it be compiled?

**Comment by tpunix** [comment]
From your error message, you need install freetype and zlib first.

**Comment by nassau-tk** [comment]
Thnk you for teaching!!
I will try it!

**Comment by nassau-tk** [comment]
Thank you!
I got install PGF Tool!!
And, I could make a "Japanese & Chinese Mix PGF"!!
It's Greate!!
