### ISSUE TITLE
I want create "ltn8~15.pgf" (Small Latin).

### ISSUE THREAD

**Issue by nassau-tk** [tpunix/pgftool#3]
I could create jpn0.pgf/ltn0~7.pgf by this tool.
Thank you!!

And,I try to create ltn8~15.pgf now.
Glyph hight & width is maybe good but line spaces is maybe too large.

Is it problem of my way?

[Dump info of Created ltn8.pgf]
![image](https://user-images.githubusercontent.com/48179091/100329405-f43a3f00-3010-11eb-8976-6b857c843ee4.png)

[Win Ascent & Win Descent set value 0. But it will not change any style.]
![image](https://user-images.githubusercontent.com/48179091/100329503-116f0d80-3011-11eb-96f9-4ad77c7c5900.png)

[Real ltn12.pgf on Lunar.]
![image](https://user-images.githubusercontent.com/48179091/100330128-e6d18480-3011-11eb-9386-b5f290613bf1.png)
![image](https://user-images.githubusercontent.com/48179091/100330163-f355dd00-3011-11eb-8c0a-af1fabb48f92.png)

[Maked ltn12.pgf on Lunar.] (ltn8.pgf rename to 12)
![image](https://user-images.githubusercontent.com/48179091/100330439-4c257580-3012-11eb-9337-47da95f60f0d.png)
![image](https://user-images.githubusercontent.com/48179091/100330496-5f384580-3012-11eb-818f-2d5b9cd8bc5e.png)

I think "Warning screen" will looks good size.
But,The  line spaces to large that In game conversation window.

If you have any advice or solved way.
Please,Help me.

**Comment by tpunix** [comment]
you can change ascender/decsender value and test again.
the offset in pgf file:
    0xd4: ascender
    0xd8: descender
this value are in fixed 26.6 format.

**Comment by nassau-tk** [comment]
Thank you!

And,Sorry please teach me.
When should I change Ascender & Descender?
1. At making TTF?
2. At useing pgftool? (Oqtion Command?)

**Comment by tpunix** [comment]
Use a hexedit tool. Modify the generated pgf file.

**Comment by nassau-tk** [comment]
Thank you!

I will learning about hexedit tools and try it!

**Comment by nassau-tk** [comment]
When you can tell a recommended tool, it's lucky.

**Comment by nassau-tk** [comment]
Hello.
I'm creating small latin pgf by your helping. 
I could changed the Ascender & Descender value.
Other people helped me too.

And other problem(question) is born now.

"h_size" (horizonal size?)
"V_size" (vertical size?)
"Real PSP PGF" is "7.000000" both.
Is it should be fix to match?

Because,some games not fixed by Asceder & Descender value.

If you know about this.
Please,Teach me!!

![image](https://user-images.githubusercontent.com/48179091/100495422-11951780-318f-11eb-8d1c-9ded06402b48.png)

[Real PSP ltn9.pgf]
![image](https://user-images.githubusercontent.com/48179091/100495598-540b2400-3190-11eb-89db-0393f139ca22.png)

[My Created ltn9.pgf]
![image](https://user-images.githubusercontent.com/48179091/100495579-405fbd80-3190-11eb-8e90-7a21c2b46193.png)

**Comment by tpunix** [comment]
try "max glyph height"? offset is 0xfe.

**Comment by nassau-tk** [comment]
OK!
I will try it!!

**Comment by nassau-tk** [comment]
hm....
I was set max glyph hight 14 to 7.
But,It's not changed any.

**Comment by nassau-tk** [comment]
I tried changing value of some address.
But,I could't find value of "h_size"&"v_size".
hm....I'm into the deadlock now.:sweat_smile:

**Comment by nassau-tk** [comment]
Hello master!
I could make all of PGF!

We needed change between "max_hor_bearing_X" and "max_vert_dimension" too.
Those value needed match or control to near on "Original".

Thank you for your help and tool!!

**Comment by tpunix** [comment]
That's great!
