### ISSUE TITLE
dump_pgf can't work on "Official kr0.pgf".

### ISSUE THREAD

**Issue by nassau-tk** [tpunix/pgftool#4]
dump_pgf can't work for "official kr0.pgf".

![image](https://user-images.githubusercontent.com/48179091/104283550-07876800-54f4-11eb-8d23-61fc63c33ee1.png)

It's not appear any error warning.:open_mouth:

And, Official kr0.pgf is can't load on PPSSPP too.:confounded:
But, Our custom kr0.pgf  is working.:sweat_smile:

Reference of kr0.pgf issue.
https://github.com/hrydgard/ppsspp/issues/13190

If you have any idea then please help!

**Comment by tpunix** [comment]
official koren font has special format. Glyph are formed by many small glyph.
I dont know anything about koren, so it is unsupport in pgftool. and unsupport in PPSSPP.

**Comment by nassau-tk** [comment]
Oh!!
Really!?

I should have told you more fast!
I felt a value on the Korean custom PGF font made.

OK. I understood about kr0.pgf.

Thank you master!
